#!/usr/bin/bash
echo " ================ test ex00 ================= "
cd ~/Desktop/ds_3/ex00
cp ~/Documents/outer/42_python_piscine/ds_3_oop/ex00/tester.py .
python3 ./tester.py
echo " ================ test ex01 ================= "
cd ~/Desktop/ds_3/ex01
cp ~/Documents/outer/42_python_piscine/ds_3_oop/ex01/tester.py .
python3 ./tester.py
echo " ================ test ex02 ================= "
cd ~/Desktop/ds_3/ex02
cp ~/Documents/outer/42_python_piscine/ds_3_oop/ex02/tester.py .
python3 ./tester.py
echo " ================ test ex03 ================= "
cd ~/Desktop/ds_3/ex03
cp ~/Documents/outer/42_python_piscine/ds_3_oop/ex03/tester.py .
python3 ./tester.py
echo " ================ test ex04 ================= "
cd ~/Desktop/ds_3/ex04
cp ~/Documents/outer/42_python_piscine/ds_3_oop/ex04/tester.py .
python3 ./tester.py
